export interface FeatureCategory {
  title: string
  items: readonly string[]
}

export const FEATURE_LIST: readonly FeatureCategory[] = [
  {
    title: 'Instant Arcade Racing',
    items: [
      'Race directly from any shared URL.',
      'Drive a fast low-poly 3D arcade car.',
      'Start every race with a 3, 2, 1, GO countdown.',
      'Loop laps forever and chase better times.',
      'Restart a lap at any time.',
      'Pause and resume mid-race.',
      'Exit with a session summary.',
    ],
  },
  {
    title: 'Custom URL Tracks',
    items: [
      'Every URL can be its own track.',
      'Create a new track when a URL has no track yet.',
      'Race the latest version of any track.',
      'Race older track versions with version links.',
      'Fork older versions into new edits.',
      'Share tracks by sending the URL.',
      'Star favorite tracks.',
      'Browse recent and existing tracks.',
    ],
  },
  {
    title: 'Track Editor',
    items: [
      'Build tracks on a snap-to-grid editor.',
      'Place straights.',
      'Place sharp left and right turns.',
      'Place S-curves.',
      'Place wide sweep turns.',
      'Rotate track pieces.',
      'Undo and redo edits.',
      'Pan and zoom around the editor.',
      'Select rectangular groups of pieces.',
      'Move selected pieces.',
      'Rotate selected pieces.',
      'Flip selected pieces horizontally or vertically.',
      'Apply starter track templates.',
      'Set custom checkpoint locations.',
      'Adjust checkpoint count.',
      'Pick a track biome.',
      'Add decorative props.',
      'Save validated closed-loop tracks.',
      'Create versioned track updates.',
    ],
  },
  {
    title: 'Track Themes',
    items: [
      'Race in a classic forest setting.',
      'Race in snow.',
      'Race in desert.',
      'Race on beach-themed tracks.',
      'Race in mountain scenery.',
      'Race in city scenery.',
      'Add trees, rocks, cacti, palms, buildings, snow piles, and pines.',
      'Toggle scenery visibility.',
      'Show red-and-white kerbs on corners.',
      'Toggle kerbs on or off.',
    ],
  },
  {
    title: 'Weather And Lighting',
    items: [
      'Choose noon lighting.',
      'Choose morning lighting.',
      'Choose sunset lighting.',
      'Choose night lighting.',
      'Race in clear weather.',
      'Race in cloudy weather.',
      'Race in fog.',
      'Race in rain.',
      'Race in snow.',
      'See falling rain particles.',
      'See falling snow particles.',
      "Let track creators define the intended mood.",
      "Respect or override a track creator's mood.",
      'Enable time-of-day cycling.',
    ],
  },
  {
    title: 'Camera Views',
    items: [
      'Use chase far view.',
      'Use chase close view.',
      'Use cockpit view.',
      'Use dashboard view.',
      'Use hood view.',
      'Use bumper view.',
      'Tune camera height.',
      'Tune camera distance.',
      'Tune look-ahead.',
      'Tune follow speed.',
      'Tune field of view.',
      'Use an in-race rearview mirror.',
    ],
  },
  {
    title: 'Driving And Handling',
    items: [
      'Arcade car physics.',
      'Speed-sensitive steering.',
      'Handbrake slides.',
      'Off-track slowdown.',
      'Four-wheel road contact.',
      'Optional manual shifting per track.',
      'Automatic transmission for simpler tracks.',
      'Gear display for manual tracks.',
      'Tune car handling in Setup.',
    ],
  },
  {
    title: 'Controls',
    items: [
      'Keyboard driving.',
      'Touch driving.',
      'Gamepad driving.',
      'Analog gamepad triggers.',
      'Remappable keyboard controls.',
      'Remappable gamepad controls.',
      'Touch joystick options.',
      'Dedicated pause control.',
      'Dedicated restart control.',
      'Dedicated shift controls.',
    ],
  },
  {
    title: 'Car Customization',
    items: [
      'Choose car paint color.',
      'Add a racing number.',
      'Pick racing number plate color.',
      'Pick racing number text color.',
      'Show or hide the racing number.',
      'Use working headlights.',
      'Set headlights to Off, Auto, or On.',
      'Use working brake lights.',
      'Set brake lights to Off, Auto, or On.',
    ],
  },
  {
    title: 'Race HUD',
    items: [
      'Current lap timer.',
      'Projected lap time.',
      'Last lap time.',
      'Session best.',
      'All-time best.',
      'Track record.',
      'Lap counter.',
      'Racer initials.',
      'Speedometer.',
      'Minimap.',
      'Rearview mirror.',
      'Wrong-way warning.',
      'Off-track warning.',
      'Drift score.',
      'Split delta.',
      'Pace notes.',
      'Ghost gap display.',
      'Rival status.',
      'Top-speed personal best alert.',
      'Rank toast.',
      'Personal best celebration.',
      'Track record celebration.',
    ],
  },
  {
    title: 'Leaderboards',
    items: [
      'Per-track-version leaderboards.',
      'Automatic lap submission.',
      'Personal best highlighting.',
      'Track record display.',
      'Sort leaderboard by rank.',
      'Sort leaderboard by racer.',
      'Sort leaderboard by lap time.',
      'Sort leaderboard by date.',
      'Browse leaderboard pages beyond the top 100.',
      'Show input device badges.',
      'Open lap details.',
      'View the setup used for a lap.',
      "Try another racer's setup.",
      'Race a specific track version.',
      'Race against a leaderboard rival.',
    ],
  },
  {
    title: 'Ghosts And Challenges',
    items: [
      'Race against the top ghost.',
      'Race against a selected rival ghost.',
      'See ghost nameplates.',
      'Challenge a friend.',
      'Race a friend challenge ghost.',
      'Share challenge links.',
    ],
  },
  {
    title: 'Progress And Stats',
    items: [
      'Track personal best history.',
      'Track session lap history.',
      'Show lifetime stats.',
      'Show track stats.',
      'Earn achievements.',
      'View achievements.',
      'View trophies and medals.',
      'Track personal best streaks.',
      'Track daily streaks.',
      'View daily challenge widgets.',
      'View activity widgets.',
      'View most-played tracks.',
      'View your tracks.',
      'View your best laps.',
    ],
  },
  {
    title: 'Setup And Tuning',
    items: [
      'Tune max speed.',
      'Tune acceleration.',
      'Tune braking.',
      'Tune reverse acceleration.',
      'Tune rolling friction.',
      'Tune low-speed steering.',
      'Tune high-speed steering.',
      'Tune minimum steering speed.',
      'Tune off-track max speed.',
      'Tune off-track drag.',
      'Save setup choices with leaderboard runs.',
      'Reuse the last loaded setup.',
      'Test setups in the tuning lab.',
      'Review speed traces.',
      'Review off-track events.',
    ],
  },
  {
    title: 'Audio',
    items: [
      'Title music.',
      'Race music.',
      'Pause music.',
      'Speed-reactive race music.',
      'Per-track music flavor.',
      'Optional initials-based music flavor.',
      'Countdown beeps.',
      'Engine sound.',
      'Tire skid sound.',
      'Off-track rumble sound.',
      'Finish-line stinger.',
      'Personal best fanfare.',
      'Track record fanfare.',
      'Wrong-way warning sound.',
      'Achievement unlock sound.',
      'UI click sounds.',
      'Music volume controls.',
      'SFX volume controls.',
    ],
  },
  {
    title: 'Haptics And Controller Rumble',
    items: [
      'Touch vibration feedback.',
      'Gamepad rumble.',
      'Engine rumble.',
      'Off-track rumble.',
      'Slip rumble.',
      'Brake-lock rumble.',
      'Lap completion rumble.',
      'Personal best rumble.',
      'Track record rumble.',
      'Wrong-way rumble.',
      'Achievement rumble.',
      'Xbox One and Series trigger rumble.',
      'Strong motor intensity slider.',
      'Weak motor intensity slider.',
      'Separate Off, Auto, and On modes.',
    ],
  },
  {
    title: 'Menus And Player Tools',
    items: [
      'Title screen.',
      'Load existing track menu.',
      'How to play.',
      'Pause menu.',
      'Tabbed settings.',
      'Leaderboards pane.',
      'Lap history pane.',
      'PB history pane.',
      'Stats pane.',
      'Achievements pane.',
      'Setup pane.',
      'Photo mode.',
      'Feature List credits screen.',
      'Share track.',
      'Star track.',
      'Edit initials in Settings.',
    ],
  },
  {
    title: 'Feedback',
    items: [
      'Send feedback from the pause menu.',
      'Include a screenshot with feedback.',
      'Include captured console logs with feedback.',
    ],
  },
]

export const FEATURE_LIST_ITEM_COUNT = FEATURE_LIST.reduce(
  (total, category) => total + category.items.length,
  0,
)
